export const GET_CHARACTERS = "GET_CHARACTERS";
export const GET_PLANETS = "GET_PLANETS";
export const SET_FAVORITE = "SET_FAVORITE";
export const SEARCH_FAVORITE = "SEARCH_FAVORITE";
export const SET_CHARACTERS_ERROR = "SET_CHARACTERS_ERROR";
export const SET_PLANETS_ERROR = "SET_PLANETS_ERROR";
